# Generated by Django 5.1 on 2024-08-27 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Clinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateField()),
                ('descricao_atendimento', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consulta.clinicopaciente')),
            ],
        ),
        migrations.CreateModel(
            name='PsicologoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateField()),
                ('descricao_atendimento', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consulta.psicologopaciente')),
            ],
        ),
        migrations.CreateModel(
            name='PsiquiatraPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Psiquiatra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateField()),
                ('descricao_atendimento', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consulta.psiquiatrapaciente')),
            ],
        ),
    ]
